// Code generated by "stringer -type=RateSchemaFieldName -linecomment"; DO NOT EDIT.

package schema

import "strconv"

const _RateSchemaFieldName_name = "timepairbuy_ratesell_ratebuy_sanity_ratesell_sanity_ratefrom_blockto_blockreserve"

var _RateSchemaFieldName_index = [...]uint8{0, 4, 8, 16, 25, 40, 56, 66, 74, 81}

func (i RateSchemaFieldName) String() string {
	if i < 0 || i >= RateSchemaFieldName(len(_RateSchemaFieldName_index)-1) {
		return "RateSchemaFieldName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RateSchemaFieldName_name[_RateSchemaFieldName_index[i]:_RateSchemaFieldName_index[i+1]]
}
