run:
  deadline: 5m
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - unused
linters:
  disable-all: true
  enable:
    - errcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - typecheck
    - govet
    - staticcheck
    - ineffassign
    - deadcode
    - revive
    - stylecheck
    - unconvert
    - goconst
    - goimports
    - exportloopref
