language: go

go:
  - 1.11.x

services:
  - docker
  - postgresql

addons:
  postgresql: "9.5"

before_install:
  - docker run -d -p "127.0.0.1:8086:8086" influxdb:1.6.3-alpine

env:
  global:
    - GOMETALINTER_VERSION=2.0.11
    - GO111MODULE=on
    - PATH=$PATH:${TRAVIS_HOME}/gometalinter/gometalinter-${GOMETALINTER_VERSION}-linux-amd64

matrix:
  include:
    - env:
      - BUILD_PART: 1
    - env:
      - BUILD_PART: 2
    - env:
      - BUILD_PART: 3

install:
  - ./.travis/gometalinter-install.sh

cache:
  directories:
  - ${TRAVIS_HOME}/gometalinter/gometalinter-${GOMETALINTER_VERSION}-linux-amd64

before_script:
  - psql -c "CREATE DATABASE reserve_stats;" -U postgres
  - psql -c "CREATE USER reserve_stats WITH PASSWORD 'reserve_stats';" -U postgres

script:
  - bash .travis/docker_build.sh

deploy:
  - provider: script
    script: bash .travis/docker_push.sh
    on:
      all_branches: true

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: dev-stats-docs.knstats.com
    region: ap-southeast-1
    acl: public_read
    local_dir: apidocs/build
    skip_cleanup: true
    on:
      branch: develop
      condition: $BUILD_PART = 3
