language: go

go:
  # pin go version to avoid test failure
  # https://travis-ci.com/KyberNetwork/reserve-stats/jobs/191022971
  # /home/travis/.gimme/versions/go1.12.2.linux.amd64/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
  # /usr/bin/ld: /tmp/go-link-820513584/000006.o: unrecognized relocation (0x2a) in section `.text'
  # /usr/bin/ld: final link failed: Bad value
  # collect2: error: ld returned 1 exit status
  # happens with
  # - 1.11.6
  # - go 1.11.7
  - 1.14.9

services:
  - docker
  - postgresql

addons:
  postgresql: "10"

before_install:
  - docker run -d -p "127.0.0.1:8086:8086" influxdb:1.7.1-alpine

env:
  global:
    - GOLANGCI_LINT_VERSION=1.27.0
    - GO111MODULE=on

matrix:
  include:
    - env:
        - BUILD_PART: 1
    - env:
        - BUILD_PART: 2
    - env:
        - BUILD_PART: 3
    - env:
        - BUILD_PART: 4
    - env:
        - BUILD_PART: 5

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b ${TRAVIS_HOME}/bin v${GOLANGCI_LINT_VERSION} || curl  -sfL  https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ${TRAVIS_HOME}/bin v${GOLANGCI_LINT_VERSION} 

before_script:
  - psql -c "CREATE DATABASE reserve_stats;" -U postgres
  - psql -c "CREATE USER reserve_stats WITH PASSWORD 'reserve_stats';" -U postgres
  - psql -c "ALTER USER reserve_stats CREATEDB;" -U postgres

script:
  - bash .travis/golangci.sh

deploy:
  - provider: script
    script: bash .travis/docker.sh
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^develop|staging|master|reserve-v4$

  - provider: script
    script: bash .travis/docker.sh
    on:
      tags: true

  - provider: script
    script: bash .travis/awx_job_launch.sh $TRAVIS_BRANCH
    on:
      all_branches: true

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: dev-stats-docs.knstats.com
    region: ap-southeast-1
    acl: public_read
    local_dir: apidocs/build
    skip_cleanup: true
    on:
      branch: develop
      condition: $BUILD_PART = 5

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: dev-accounting-docs.knstats.com
    region: ap-southeast-1
    acl: public_read
    local_dir: accounting/apidocs/build
    skip_cleanup: true
    on:
      branch: develop
      condition: $BUILD_PART = 5
