language: go

go:
  - 1.11.x

services:
  - docker
  - postgresql

addons:
  postgresql: "9.5"

before_install:
  - docker run -d -p "127.0.0.1:8086:8086" influxdb:1.6.3-alpine

env:
  global:
    - GOMETALINTER_VERSION=2.0.11
    - GO111MODULE=on
    - PATH=$PATH:${TRAVIS_HOME}/gometalinter/gometalinter-${GOMETALINTER_VERSION}-linux-amd64

matrix:
  include:
    - env:
      - MODULE=reserverates
    - env:
      - MODULE=tradelogs
    - env:
      - MODULE=users
    - env:
      - MODULE=others

install:
  - ./.travis/gometalinter-install.sh

cache: 
  directories:
  - ${TRAVIS_HOME}/gometalinter/gometalinter-${GOMETALINTER_VERSION}-linux-amd64

before_script:
  - psql -c "CREATE DATABASE reserve_stats;" -U postgres
  - psql -c "CREATE USER reserve_stats WITH PASSWORD 'reserve_stats';" -U postgres

script:
  - bash .travis/docker_build.sh

deploy:
  - provider: script
    script: bash .travis/docker_push.sh
    on:
      all_branches: true
