language: go

go:
  - 1.11.x

services:
  - docker
  - postgresql

addons:
  postgresql: "9.5"

before_install:
  - docker run -d -p "127.0.0.1:8086:8086" influxdb:1.7.1-alpine

env:
  global:
    - GOLANGCI_LINT_VERSION=1.15.0
    - GO111MODULE=on

matrix:
  include:
    - env:
        - BUILD_PART: 1
    - env:
        - BUILD_PART: 2
    - env:
        - BUILD_PART: 3
    - env:
        - BUILD_PART: 4

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b ${TRAVIS_HOME}/bin v${GOLANGCI_LINT_VERSION}

before_script:
  - psql -c "CREATE DATABASE reserve_stats;" -U postgres
  - psql -c "CREATE USER reserve_stats WITH PASSWORD 'reserve_stats';" -U postgres

script: skip

deploy:
  - provider: script
    script: bash .travis/docker_build.sh
    on:
      tags: true
      branch:
        - develop
        - staging
        - master

  - provider: script
    script: bash .travis/docker_push.sh
    on:
      tags: true
      branch:
        - develop
        - staging
        - master

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: dev-stats-docs.knstats.com
    region: ap-southeast-1
    acl: public_read
    local_dir: apidocs/build
    skip_cleanup: true
    on:
      branch: develop
      condition: $BUILD_PART = 4
