language: go

go:
  - 1.11.x

services:
  - postgresql

addons:
  postgresql: "9.5"

install:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

before_script:
  - psql -c "CREATE DATABASE reserve_stats;" -U postgres
  - psql -c "CREATE USER reserve_stats WITH PASSWORD 'reserve_stats';" -U postgres

script:
  - gometalinter --config=gometalinter.json ./...
  - env GO111MODULE=on go build -v -mod=vendor ./...
  - env GO111MODULE=on go test -v -mod=vendor ./...
