version: '3.1'
services:
  postgres:
    image: 'postgres:12-alpine'
    volumes:
      - './init-postgres-db.sh:/docker-entrypoint-initdb.d/init-postgres-db.sh'
      - './data/postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: reserve_stats
      POSTGRES_USER: reserve_stats
      POSTGRES_PASSWORD: reserve_stats
    ports:
      - '127.0.0.1:5432:5432'
  redis:
    image: 'redis:5.0.2-alpine'
    volumes:
      - './data/redis:/var/lib/redis/'
    ports:
      - '127.0.0.1:6379:6379'
