version: '3.1'
services:
  kapacitor:
    image: 'kapacitor:1.5.2-alpine'
    volumes:
      - './data/kapacitor:/var/lib/kapacitor/'
      - './ticks:/ticks'
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
    ports:
      - '127.0.0.1:9092:9092'
  postgres:
    image: 'postgres:10-alpine'
    volumes:
      - './init-postgres-db.sh:/docker-entrypoint-initdb.d/init-postgres-db.sh'
      - './data/postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: reserve_stats
      POSTGRES_USER: reserve_stats
      POSTGRES_PASSWORD: reserve_stats
    ports:
      - '127.0.0.1:5432:5432'
  redis:
    image: 'redis:5.0.2-alpine'
    volumes:
      - './data/redis:/var/lib/redis/'
    ports:
      - '127.0.0.1:6379:6379'
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - '127.0.0.1:9000:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: reserve_stats@localhost
      PGADMIN_DEFAULT_PASSWORD: reserve_stats
