version: '3.1'

services:
  influxdb:
    image: influxdb:1.6.3-alpine
    volumes:
      - ./data/influxdb:/var/lib/influxdb/
    ports:
      - "8086:8086"
  postgres:
    image: postgres:9.5.14-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: reserve-stats
      POSTGRES_USER: reserve-stats
      POSTGRES_PASSWORD: reserve-stats
