// Code generated by "stringer -type=FieldName -linecomment"; DO NOT EDIT.

package tradelog

import "strconv"

const _FieldName_name = "timeblock_numbertx_hasheth_receival_senderuser_addrsrc_addrdst_addrcountryipeth_rate_providerdst_rsv_addrsrc_rsv_addreth_receival_amountsrc_amountdst_amounteth_usd_rateeth_amountfiat_amountintegration_appwallet_addrlog_indexsrc_burn_feedst_burn_fee"

var _FieldName_index = [...]uint8{0, 4, 16, 23, 42, 51, 59, 67, 74, 76, 93, 105, 117, 136, 146, 156, 168, 178, 189, 204, 215, 224, 236, 248}

func (i FieldName) String() string {
	if i < 0 || i >= FieldName(len(_FieldName_index)-1) {
		return "FieldName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FieldName_name[_FieldName_index[i]:_FieldName_index[i+1]]
}
