// Code generated by "stringer -type=FieldName -linecomment"; DO NOT EDIT.

package tradelog

import "strconv"

const _FieldName_name = "timeblock_numbertx_hasheth_receival_senderuser_addrsrc_addrdst_addrcountryipeth_rate_providerdst_rsv_addrssrc_rsv_addrseth_receival_amountsrc_amountdst_amounteth_usd_rateeth_amountfiat_amountlog_index"

var _FieldName_index = [...]uint8{0, 4, 16, 23, 42, 51, 59, 67, 74, 76, 93, 106, 119, 138, 148, 158, 170, 180, 191, 200}

func (i FieldName) String() string {
	if i < 0 || i >= FieldName(len(_FieldName_index)-1) {
		return "FieldName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FieldName_name[_FieldName_index[i]:_FieldName_index[i+1]]
}
