// Code generated by "stringer -type=AddressType -linecomment"; DO NOT EDIT.

package common

import "strconv"

const _AddressType_name = "reservepricing_operatorsanity_operatorintermediate_operatorcex_deposit_addresscompany_walletdeposit_operator"

var _AddressType_index = [...]uint8{0, 7, 23, 38, 59, 78, 92, 108}

func (i AddressType) String() string {
	if i < 0 || i >= AddressType(len(_AddressType_index)-1) {
		return "AddressType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AddressType_name[_AddressType_index[i]:_AddressType_index[i+1]]
}
