// Code generated by "stringer -type=BinanceWithdrawStatus -linecomment"; DO NOT EDIT.

package common

import "strconv"

const _BinanceWithdrawStatus_name = "email-sentcancelledawaiting-approvalrejectedprocessingfailurecompleted"

var _BinanceWithdrawStatus_index = [...]uint8{0, 10, 19, 36, 44, 54, 61, 70}

func (i BinanceWithdrawStatus) String() string {
	if i < 0 || i >= BinanceWithdrawStatus(len(_BinanceWithdrawStatus_index)-1) {
		return "BinanceWithdrawStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BinanceWithdrawStatus_name[_BinanceWithdrawStatus_index[i]:_BinanceWithdrawStatus_index[i+1]]
}
