// Code generated by "stringer -type=CexName -linecomment"; DO NOT EDIT.

package common

import "strconv"

const _CexName_name = "binancehuobi"

var _CexName_index = [...]uint8{0, 7, 12}

func (i CexName) String() string {
	if i < 0 || i >= CexName(len(_CexName_index)-1) {
		return "CexName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CexName_name[_CexName_index[i]:_CexName_index[i+1]]
}
