// Code generated by "stringer -type=OrderState -linecomment"; DO NOT EDIT.

package common

import "strconv"

const _OrderState_name = "pre-submittedsubmittingsubmittedpartial-filledpartial-canceledfilledcanceledfailed"

var _OrderState_index = [...]uint8{0, 13, 23, 32, 46, 62, 68, 76, 82}

func (i OrderState) String() string {
	i -= 1
	if i < 0 || i >= OrderState(len(_OrderState_index)-1) {
		return "OrderState(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _OrderState_name[_OrderState_index[i]:_OrderState_index[i+1]]
}
