// Code generated by "stringer -type=Deployment -linecomment"; DO NOT EDIT.

package deployment

import "strconv"

const _Deployment_name = "productionstaging"

var _Deployment_index = [...]uint8{0, 10, 17}

func (i Deployment) String() string {
	if i < 0 || i >= Deployment(len(_Deployment_index)-1) {
		return "Deployment(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Deployment_name[_Deployment_index[i]:_Deployment_index[i+1]]
}
