// Code generated by "stringer -type=FieldName -linecomment"; DO NOT EDIT.

package walletstats

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Time-0]
	_ = x[UniqueAddresses-1]
	_ = x[ETHVolume-2]
	_ = x[USDVolume-3]
	_ = x[TotalTrade-4]
	_ = x[USDPerTrade-5]
	_ = x[ETHPerTrade-6]
	_ = x[TotalBurnFee-7]
	_ = x[NewUniqueAddresses-8]
	_ = x[KYCedAddresses-9]
	_ = x[WalletAddress-10]
}

const _FieldName_name = "timeunique_addresseseth_volumeusd_volumetotal_tradeusd_per_tradeeth_per_tradetotal_burn_feenew_unique_addresseskycedwallet_addr"

var _FieldName_index = [...]uint8{0, 4, 20, 30, 40, 51, 64, 77, 91, 111, 116, 127}

func (i FieldName) String() string {
	if i < 0 || i >= FieldName(len(_FieldName_index)-1) {
		return "FieldName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FieldName_name[_FieldName_index[i]:_FieldName_index[i+1]]
}
