// Code generated by "stringer -type=runningMode -linecomment"; DO NOT EDIT.

package app

import "strconv"

const _runningMode_name = "devprod"

var _runningMode_index = [...]uint8{0, 3, 7}

func (i runningMode) String() string {
	if i < 0 || i >= runningMode(len(_runningMode_index)-1) {
		return "runningMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _runningMode_name[_runningMode_index[i]:_runningMode_index[i+1]]
}
