// Code generated by "stringer -type=ReplyStatus -linecomment"; DO NOT EDIT.

package huobi

import "strconv"

const _ReplyStatus_name = "okerror"

var _ReplyStatus_index = [...]uint8{0, 2, 7}

func (i ReplyStatus) String() string {
	if i < 0 || i >= ReplyStatus(len(_ReplyStatus_index)-1) {
		return "ReplyStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReplyStatus_name[_ReplyStatus_index[i]:_ReplyStatus_index[i+1]]
}
