// Code generated by "stringer -type=TestMode -linecomment"; DO NOT EDIT.

package testutil

import "strconv"

const _TestMode_name = "InternalTestExternalTest"

var _TestMode_index = [...]uint8{0, 12, 24}

func (i TestMode) String() string {
	if i < 0 || i >= TestMode(len(_TestMode_index)-1) {
		return "TestMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TestMode_name[_TestMode_index[i]:_TestMode_index[i+1]]
}
