package influx

import "strconv"

// Code generated by "stringer -type=RateSchemaFieldName -linecomment"; DO NOT EDIT.

const _RateSchemaFieldName_name = "timereturn_timepairbuy_ratesell_ratebuy_sanity_ratesell_sanity_rateblock_numberreserve"

var _RateSchemaFieldName_index = [...]uint8{0, 4, 15, 19, 27, 36, 51, 67, 79, 86}

func (i RateSchemaFieldName) String() string {
	if i < 0 || i >= RateSchemaFieldName(len(_RateSchemaFieldName_index)-1) {
		return "RateSchemaFieldName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RateSchemaFieldName_name[_RateSchemaFieldName_index[i]:_RateSchemaFieldName_index[i+1]]
}
