package schema

import "strconv"

// Code generated by "stringer -type=RateSchemaFieldName -linecomment"; DO NOT EDIT.

const _RateSchemaFieldName_name = "timepairbuy_ratesell_ratebuy_sanity_ratesell_sanity_rateblock_numberreserve"

var _RateSchemaFieldName_index = [...]uint8{0, 4, 8, 16, 25, 40, 56, 68, 75}

func (i RateSchemaFieldName) String() string {
	if i < 0 || i >= RateSchemaFieldName(len(_RateSchemaFieldName_index)-1) {
		return "RateSchemaFieldName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RateSchemaFieldName_name[_RateSchemaFieldName_index[i]:_RateSchemaFieldName_index[i+1]]
}
