FROM golang:1.11-stretch AS build-env

COPY . /reserve-stats
WORKDIR /reserve-stats/accounting/cmd/accounting-reserve-tokens-api
RUN go build -v -mod=vendor -o /accounting-reserve-tokens-api

FROM debian:stretch
COPY --from=build-env /accounting-reserve-tokens-api /

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/accounting-reserve-tokens-api"]
