FROM golang:1.11-stretch AS build-env

COPY . /reserve-stats
WORKDIR /reserve-stats/accounting/cmd/accounting-binance-withdraw-fetcher
RUN go build -v -mod=vendor -o /accounting-binance-withdraw-fetcher

FROM debian:stretch
COPY --from=build-env /accounting-binance-withdraw-fetcher /

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/accounting-binance-withdraw-fetcher"]
