FROM golang:1.11-stretch AS build-env

COPY . /reserve-stats
WORKDIR /reserve-stats/users/cmd/users-api
RUN go build -v -mod=vendor -o /users-api

FROM debian:stretch
COPY --from=build-env /users-api /

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/users-api"]
