FROM golang:1.12-stretch AS build-env

COPY . /reserve-stats
WORKDIR /reserve-stats/accounting/cmd/accounting-cex-trades-api
RUN go build -v -mod=vendor -o /accounting-cex-trades-api

FROM debian:stretch
COPY --from=build-env /accounting-cex-trades-api /

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENV HTTP_ADDRESS=0.0.0.0:8010
EXPOSE 8010

ENTRYPOINT ["/accounting-cex-trades-api"]
