FROM golang:1.17 AS build-env

COPY . /reserve-stats
WORKDIR /reserve-stats/accounting/cmd/accounting-0x-trade-post-processor
RUN go build -v -mod=mod -o /accounting-0x-trade-post-processor

FROM debian:stretch
COPY --from=build-env /accounting-0x-trade-post-processor /

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/accounting-0x-trade-post-processor"]
