FROM golang:1.11-stretch AS build-env

COPY . /reserve-stats
WORKDIR /reserve-stats/tradelogs/cmd/trade-logs-postprocessor
RUN go build -v -mod=vendor -o /trade-logs-postprocessor

FROM debian:stretch
COPY --from=build-env /trade-logs-postprocessor /

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/trade-logs-postprocessor"]
