FROM golang:1.11-stretch AS build-env

COPY . /reserve-stats
WORKDIR /reserve-stats/gateway/cmd
RUN go build -v -mod=vendor -o /gateway

FROM debian:stretch
COPY --from=build-env /gateway /

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/gateway"]
