FROM golang:1.14-stretch AS build-env

COPY . /reserve-stats
WORKDIR /reserve-stats/gateway/cmd
RUN go build -v -mod=mod -o /gateway

FROM debian:stretch
COPY --from=build-env /gateway /

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENV HTTP_ADDRESS=0.0.0.0:8005
EXPOSE 8005
ENTRYPOINT ["/gateway"]
