FROM golang:1.11-stretch AS build-env

COPY . /reserve-stats
WORKDIR /reserve-stats/accounting/cmd/accounting-huobi-withdrawal-history
RUN go build -v -mod=vendor -o /accounting-huobi-withdrawal-history

FROM debian:stretch
COPY --from=build-env /accounting-huobi-withdrawal-history /

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/accounting-huobi-withdrawal-history"]
