FROM golang:1.12.4-stretch AS build-env

COPY . /reserve-stats
WORKDIR /reserve-stats/accounting/cmd/accounting-cex-withdrawals-api
RUN go build -v -mod=vendor -o /accounting-cex-withdrawals-api

FROM debian:stretch
COPY --from=build-env /accounting-cex-withdrawals-api /

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENV HTTP_ADDRESS=0.0.0.0:8014
EXPOSE 8014

ENTRYPOINT ["/accounting-cex-withdrawals-api"]
