FROM golang:1.14-stretch AS build-env

COPY . /reserve-stats
WORKDIR /reserve-stats/accounting/cmd/accounting-binance-deposit-fetcher
RUN go build -v -mod=mod -o /accounting-binance-deposit-fetcher

FROM debian:stretch
COPY --from=build-env /accounting-binance-deposit-fetcher /

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/accounting-binance-deposit-fetcher"]
