// Code generated by "stringer -type=TradeLogSchemaFieldName -linecomment"; DO NOT EDIT.

package schema

import "strconv"

const _TradeLogSchemaFieldName_name = "timeblock_numbertx_hasheth_receival_senderuser_addrsrc_addrdst_addrcountryipeth_rate_providerdst_rsv_addrssrc_rsv_addrseth_receival_amountsrc_amountdst_amounteth_usd_rateeth_amountfiat_amountintegration_appwallet_addrlog_index"

var _TradeLogSchemaFieldName_index = [...]uint8{0, 4, 16, 23, 42, 51, 59, 67, 74, 76, 93, 106, 119, 138, 148, 158, 170, 180, 191, 206, 217, 226}

func (i TradeLogSchemaFieldName) String() string {
	if i < 0 || i >= TradeLogSchemaFieldName(len(_TradeLogSchemaFieldName_index)-1) {
		return "TradeLogSchemaFieldName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TradeLogSchemaFieldName_name[_TradeLogSchemaFieldName_index[i]:_TradeLogSchemaFieldName_index[i+1]]
}
