// Code generated by "stringer -type=TradeLogSchemaFieldName -linecomment"; DO NOT EDIT.

package schema

import "strconv"

const _TradeLogSchemaFieldName_name = "block_numbertx_hasheth_receival_senderuser_addrsrc_addrdst_addrcountryipeth_rate_providerdst_rsv_addrssrc_rsv_addrseth_receival_amountsrc_amountdst_amounteth_usd_rateeth_amountfiat_amountintegration_appwallet_addrlog_index"

var _TradeLogSchemaFieldName_index = [...]uint8{0, 12, 19, 38, 47, 55, 63, 70, 72, 89, 102, 115, 134, 144, 154, 166, 176, 187, 202, 213, 222}

func (i TradeLogSchemaFieldName) String() string {
	if i < 0 || i >= TradeLogSchemaFieldName(len(_TradeLogSchemaFieldName_index)-1) {
		return "TradeLogSchemaFieldName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TradeLogSchemaFieldName_name[_TradeLogSchemaFieldName_index[i]:_TradeLogSchemaFieldName_index[i+1]]
}
