name: "Reserve Stats CI"

on:
  push:
    branches:
      - "github-actions"
  workflow_dispatch:

jobs:
  # prepare the outputs to serve the next phases
  # allow branchs: all
  prepare:
    runs-on: ubuntu-18.04
    outputs:
      current_branch: ${{ steps.current_branch.outputs.value }}
      commit_tag: ${{ steps.commit_tag.outputs.value }}
    steps:
      - name: Extract branch
        shell: bash
        id: current_branch
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          echo "::set-output name=value::$BRANCH"
      - name: Get Git Commit Tag
        shell: bash
        id: commit_tag
        run: |
          COMMIT_HASH="$(echo $GITHUB_SHA | head -c7)"
          echo "::set-output name=value::$COMMIT_HASH"

  lint:
    needs:
      - prepare
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        dir:
          [
            "reserverates",
            "users",
            "gateway",
            "burnedfees",
            "tradelogs",
            "tokenratefetcher",
            "app-names",
            "accounting",
          ]
    env:
      TARGET_DIR: ${{ matrix.dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare before run lint check
        run: |
          # copy golangci
          cp .golangci.yml $TARGET_DIR
          # switch to target dir
          cd $TARGET_DIR

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.39.0
          args: -v --config ../.golangci.yml
